GET http://localhost:8000/api/projects?limit=30
###
DELETE  http://localhost:8000/api/projects/24
###
GET http://localhost:8000/api/projects?document_type=Menengah Rendah&id_prov=1&id_district=2&limit=10
###
GET http://localhost:8000/api/project-field
###
GET http://localhost:8000/api/province
###
GET http://localhost:8000/api/districts/province/12
###
GET http://localhost:8000/api/districts?idProv=12
###
GET http://localhost:8000/api/districts/12
###
GET http://localhost:8000/api/testemail
###
GET http://localhost:8000/api/kblis?sectors=true
###
GET http://localhost:8000/api/business/2
###
GET http://localhost:8000/api/kblis?sectorsByKbli=41011
###
GET http://localhost:8000/api/kbli-env-params?kbli=41011
###
GET http://localhost:8000/api/kbli-env-params?kbli=41011&businessType=true
###
GET http://localhost:8000/api/kbli-env-params?kbli=41011&businessType=Luas&unit=true
###
GET http://localhost:8000/api/kbli-env-params?kbli=41011&businessType=Luas&unit=ha
###
GET http://localhost:8000/api/project-authorities?idProject=238
###
GET http://localhost:8000/api/formulator-teams
###
GET http://localhost:8000/api/oss-projects
###
GET http://localhost:8000/api/formulators
###
GET http://localhost:8000/api/rona-awals
###
GET http://localhost:8000/api/regions?id=2
###
GET http://localhost:8000/api/support-docs?idProject=20
###
GET http://localhost:8000/api/initiatorsByEmail?email=nurika@pemrakarsaa.com
###
GET http://192.168.7.94:8000/api/clear-cache
###

POST http://localhost:8000/api/auth/login
content-type: application/json

{"email":"admin@amdalnet.dev","password":"amdalnet"}
###
POST http://localhost:8000/api/reset-password
content-type: application/json

{"email":"admin@amdalnet.dev","password":"amdalnet"}
###
POST http://localhost:8000/api/projects
content-type: application/json

{"email":"admin@amdalnet.dev","password":"amdalnet"}
###
POST http://localhost:8000/api/project-ppjk/238
content-type: application/json

{"email":"admin@amdalnet.dev","password":"amdalnet", "ppjk":"hu"}


###
GET http://localhost:8000/api/fire
###
GET http://localhost:8000/api/ossNibs?nib=9120406222016
###
GET http://localhost:8000/api/oss/sectorByKbli/27401
###
GET http://localhost:8000/api/authorities?sectors=Kehutanan
###
GET http://localhost:8000/api/oss/getField?kbli=27401&sector=Perindustrian
###
GET http://localhost:8000/api/oss/getParameterByFieldId/211
###
POST http://localhost:8000/api/oss/calculateDoc
content-type: application/json

{
    "study_approach":"terpadu",
    "listSubProject": [
        {
            "jenis": "pendukung",
            "kbli":"01465",
            "field_id":"3257",
            "sector_id":"3256",
            "params":[
                {
                    "id_param":27,
                    "id_unit":19,
                    "value":5001
                }
            ]
        },
        {
            "jenis": "utama",
            "kbli":"01465",
            "field_id":"3257",
            "sector_id":"3256",
            "params":[
                {
                    "id_param":27,
                    "id_unit":19,
                    "value":1
                }
            ]
        }
    ]
}
###